# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Harry Zhao
title: Drexel University Data Science Undergraduate
email: hz445@drexel.edu
# email_title: Email (Email title override)
phone: 445-208-8781
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: HZhao2000
github_username:  HarryZhao2000
facebook_username: people/Haoran-Zhao/100073312715161/
linkedin_username: haoranzhaods
#
## Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Harry Zhao is an undergraduate at [Drexel University](https://drexel.edu/) seeking a Bachelors of Science in <mark>Data Science</mark> and minor in <mark>Economics</mark>.

  He is incredibly insightful when confronting challenges and works immediately to solve them. He is always open minded to new opportunities and is more than able to address complex situations with strategy and confidence.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                    # other value (or no value) means no border will be displayed
        title: Data Driven Dynamical Design project(NFS)
        quote: >
          Using computer dynamic model to predict the air quality of Lanzhou
        description: | # this will include new lines to allow paragraphs
          • Build efficient downloading pipeline to collect scholarly literature in material science from various publishers
          
          • Participate in team meetings and collaborate on scholarly and scientific output
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Air Quality Prediction of Lanzhou Based on LSTM
        link: https://iopscience.iop.org/article/10.1088/1742-6596/2033/1/012085
        link_text: Artical Link
        quote: >
          Using computer dynamic model to predict the air quality of Lanzhou
        description: | # this will include new lines to allow paragraphs
          • Took charge of organizing group discussions, determining the research topics, and assigning works to the team members in the early stage.
          
          • Took charge of proposing and organizing the works related to the implementation of the project and controlling the project schedule in the middle stage.
          
          • Adopted Cross-validation method for repeated samplings and compared the prediction model with traditional RNN model.
          

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: Google Open Source Blockly Teaching Cases Data Systems
        link: http://blockly.york.moe/
        link_text: Project Link
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          A secondary development blockly cases system
        description: | # this will include new lines to allow paragraphs
          • Participate in the project design and group discussions.
          
          • Determined the four curriculum data systems of the project, including epidemic transmission simulation, butterfly effect simulation, visual simulation of sorting in computers, and simulation of different game strategies.
          
          • Learned and used mathematical modeling thinking to design the cases’ database.
          
          • Simulated the phenomena in life by combining mathematics and computer simulation methods.
          
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any
                      # other value (or no value) means no border will be displayed
        title: A New Type Box Drawing Design Based on Matplotlib
        link: https://github.com/HarryZhao2000/boxplot
        link_text: GitHub Repository
        additional_links:
        quote: >
          An attempt to improve the box plot based on practice
        description: | # this will include new lines to allow paragraphs
          • Participate in the construction of power boxplot module, drew new boxplot type methods (info boxplot, hist boxplot, and creative boxplot), improved the shortcomings of the existing methods, and built the module.
          
          • Learned to use matplotlib package knowledge and skills.
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Drexel University Metadata Research Center
        sub_title: Research Accountant
        caption: January 2022 to Present
        link: https://cci.drexel.edu/mrc/
        quote: >
          Participate in the NSF Institute for Data Driven Dynamical Design project
        description: | # this will include new lines to allow paragraphs
          • Build efficient downloading pipeline to collect scholarly literature in material science from various publishers
          
          • Participate in team meetings and collaborate on scholarly and scientific output
      - layout: right
        title: Lanzhou University DSLab
        sub_title: Team Leader for the Blockly Module
        caption: March 2021 to Present
        link: http://dslab.lzu.edu.cn/
        quote: >
          Participate in the Google Open Source Blockly Teaching Cases Data Systems project
        description: | # this will include new lines to allow paragraphs
          • Determined the four curriculum data systems of the project.
          
          • Simulated the phenomena in life by combining mathematics and computer simulation methods.
      - layout: right
        title: Hangzhou Yunge Data Technology Co., Ltd
        sub_title: Data Scientist Internship
        caption: August to September 2019
        quote: >
          Participated in the development of Instant messenger-based roadside assistance system
        description: | # this will include new lines to allow paragraphs
          • Participated in project code testing and data maintenance related works.
          
          • Assist project manager to record project progress and monitor the progress in real time.
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Lanzhou University
        sub_title: Bachelor of Science in Information Science
        caption: September 2018 to June 2021
      - layout: top-right
        title: Drexel University
        sub_title: Bachelor of Science in Information Science
        caption: Anticipated Graduation: June 2023
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Skills:
        Programing languages: Python, C, R, HTML, JavaScript, Bash, MySQL
        Tools:Git, Postgres, PyCharm, WebStorm, Apache Hadoop, Xcode, weka, DrRacket, Gephi, Jupyter Notebook Frameworks: Pandas, NumPy, Flask, TensorFlow, PaddlePaddle, scikit-learn, Beautiful Soup
        Operating System: Ubuntu(Unity), macOS(Darwin)
    
      Relevant Coursework:

        Data Structures
        Introduction to Data Science
        Information Visualization
        Social Media Data Analysis
        Business Statistics I, II
        Data Curation
        Data Science Programming I, II
        Data Mining Applications
        Linear Algebra
        Database Management Systems
        Information Retrieval Systems
        Machine Learning

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
